services:
  api:
    # Constrói a imagem a partir do Dockerfile no diretório atual (.)
    build: .
    
    # Define o nome do contêiner como 'alura-imersao-devops'
    container_name: alura-imersao-devops

    # Mapeia a porta 8000 do host para a porta 8000 do contêiner
    ports:
      - "8000:8000"

    # Monta o diretório atual no diretório /app do contêiner.
    # Isso permite que as alterações no código sejam refletidas imediatamente (hot-reload).
    # Também garante que o banco de dados 'escola.db' seja salvo no seu computador local.
    volumes:
      - .:/app
    
    # Sobrescreve o CMD do Dockerfile para usar o --reload, ideal para desenvolvimento.
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload